### ISSUE TITLE
mongo url 

### ISSUE THREAD

**Issue by xhyrom** [fnukyy/mongo_bot#1]
```js
Levels.setURL(`mongodb+srv://discordbot:${process.env.PASS}@yottstream.xzu7c.mongodb.net/myFirstDatabase?retryWrites=true&w=majority`);
```
^change this to ˘

```js
Levels.setURL(`${process.evn.mongodb}`);
```

Every user has other name of database/name of project

**Comment by fnukyy** [comment]
Hi, I don't want people to just copy it, I also want them to look at the code and understand what they need to change/update/remove. I might change it later. + It is still just few days old, there is still a lot of changes comming.
